<a href="https://colab.research.google.com/github/Syed-MuhammadTaha/NNnoLibs/blob/main/NNnoLibs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
from scipy.special import expit as sigmoid

In [101]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

class NeuralNetwork:
    # The NN constructor initializes the 2-layer NN with 4 neurons in layer 1 and a sigmoid output neuron
    """
    Dimensions (conventions established from Andrew Ng's lectures) :
      X.T : (n_x, m)
      weights1: (4, n_x)  4 neurons + n_x weights
      a[1]: (4, m)  Since W1.X
      weights2: (1, 4)
      final output: (1, m) since W2.a[1]
    """

    def __init__(self, X, y):
        self.input = X.T
        self.weights1 = np.random.rand(4, self.input.shape[0])
        self.weights2 = np.random.rand(1, 4)
        self.y = y
        self.output = np.zeros(y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.weights1, self.input))
        self.output = sigmoid(np.dot(self.weights2, self.layer1))
        return self.output
    # Lost a lot of time in getting the backprop dimensions right :(
    def backprop(self):
        d_weights2 = np.dot( (2*(self.y - self.output) * sigmoid_derivative(self.output)), self.layer1.T)
        d_weights1 = np.dot( (np.dot(self.weights2.T,2*(self.y - self.output) * sigmoid_derivative(self.output))) * sigmoid_derivative(self.layer1), self.input.T)


        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def train(self, X, y):
        self.output = self.feedforward()
        self.backprop()

In [102]:
X=np.array(([0,0,1],[0,1,1],[1,0,1],[1,1,1],[0,1,0]), dtype=float)
y=np.array(([0, 1, 1,0,1]), dtype=float)

In [105]:
NN = NeuralNetwork(X,y)
for i in range(1500): # trains the NN 1,000 times
    if i % 100 ==0:
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(NN.feedforward()))
        print ("Loss: \n" + str(np.mean(np.square(y - NN.feedforward())))) # mean sum squared loss
        print ("\n")
    NN.train(X, y)

for iteration # 0

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]
 [0. 1. 0.]]
Actual Output: 
[0. 1. 1. 0. 1.]
Predicted Output: 
[[0.78793433 0.82579244 0.84338404 0.86603773 0.80179301]]
Loss: 
0.29300494053461434


for iteration # 100

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]
 [0. 1. 0.]]
Actual Output: 
[0. 1. 1. 0. 1.]
Predicted Output: 
[[0.18007087 0.78838304 0.49761986 0.54571893 0.92336074]]
Loss: 
0.12665515913356395


for iteration # 200

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]
 [0. 1. 0.]]
Actual Output: 
[0. 1. 1. 0. 1.]
Predicted Output: 
[[0.07190205 0.87215142 0.80250018 0.23117691 0.88534136]]
Loss: 
0.0254221422716776


for iteration # 300

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]
 [0. 1. 0.]]
Actual Output: 
[0. 1. 1. 0. 1.]
Predicted Output: 
[[0.03840923 0.92392553 0.89065707 0.12937673 0.92787751]]
Loss: 
0.008231692510305111


for iteration # 400

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]
